{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.kshoji",
    "module": "midi-driver",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.kshoji",
          "module": "javax-sound-midi",
          "version": {
            "requires": "0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javax-sound-midi",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "midi-driver-0.1.8.aar",
          "url": "midi-driver-0.1.8.aar",
          "size": 82844,
          "sha512": "ab2dabd7e8f055c74f7548942ef0fba09cbf0f6301e07c09ba4e2dac3ed8ec073fd9d12a8a2022ce08a49d66d72954dd3ff55b7344814a50806fbfab5c812015",
          "sha256": "4e3564593594b1c06072a1ad84ccac73626f1928c93f6babb07d456403fa9cdc",
          "sha1": "bf136fa6dc1e6dd1661890dd5303684ae3bceb34",
          "md5": "f5452f048fdf5f03a7c537d6167d2c8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.kshoji",
          "module": "javax-sound-midi",
          "version": {
            "requires": "0.0.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javax-sound-midi",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "midi-driver-0.1.8.aar",
          "url": "midi-driver-0.1.8.aar",
          "size": 82844,
          "sha512": "ab2dabd7e8f055c74f7548942ef0fba09cbf0f6301e07c09ba4e2dac3ed8ec073fd9d12a8a2022ce08a49d66d72954dd3ff55b7344814a50806fbfab5c812015",
          "sha256": "4e3564593594b1c06072a1ad84ccac73626f1928c93f6babb07d456403fa9cdc",
          "sha1": "bf136fa6dc1e6dd1661890dd5303684ae3bceb34",
          "md5": "f5452f048fdf5f03a7c537d6167d2c8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "midi-driver-0.1.8-sources.jar",
          "url": "midi-driver-0.1.8-sources.jar",
          "size": 45678,
          "sha512": "d2e29a48b54865af19053df00b6a24efc8e9a33c0bb18f71b7071b7a1e10423f29c9e97cf8479215ac7a5ff00fd28c664303377ff20913e937748945647247c6",
          "sha256": "37be3216148b4212241b9404c6128fc865c6733e4b7a447fa31299c34dd71568",
          "sha1": "ebe7726e94eb13e533f74cdb1d4ccb3ffbeb02a4",
          "md5": "9dc6f04c80ea55d7c698460c9287e89f"
        }
      ]
    }
  ]
}
